@startuml
interface "IGenericDataRepository`1"<T> {
    GetAll() : IEnumerable<T>
    GetByID(id:object) : T
    Insert(obj:T) : bool
    Update(obj:T) : bool
    UpdateAndFetch(ojb:T) : IEnumerable<T>
    Delete(id:object) : bool
    GetSettings() : Settings
    Save() : void
}
@enduml
