@startuml
class Startup {
    + Startup(configuration:IConfiguration)
    + Configuration : IConfiguration <<get>> <<set>>
    + ConfigureServices(services:IServiceCollection) : void
    + Configure(app:IApplicationBuilder, env:IWebHostEnvironment) : void
}
@enduml
