@startuml
class VolunteerWork {
    + VolunteerWorkId : string <<get>> <<set>>
    + ShiftStart : string <<get>> <<set>>
    + ShiftEnd : string <<get>> <<set>>
    + SupervisingEmployee : string <<get>> <<set>>
    + VolunteerId : string <<get>> <<set>>
    + projectId : string <<get>> <<set>>
    + <<virtual>> employee : Employee <<get>> <<set>>
    + <<virtual>> volunteer : Volunteer <<get>> <<set>>
    + <<virtual>> project : Project <<get>> <<set>>
}
@enduml
