@startuml
class ErrorModel {
    - <<readonly>> _logger : ILogger<ErrorModel>
    + ErrorModel(logger:ILogger<ErrorModel>)
    + RequestId : string <<get>> <<set>>
    + ShowRequestId : bool <<get>>
    + OnGet() : void
}
PageModel <|-- ErrorModel
@enduml
