@startuml
class FileRepository {
    + FileRepository(context:DBContext)
    + <<async>> UploadFile(fileName:string, fileUrl:string) : Task<string>
}
class "GenericRepository`1"<T> {
}
"GenericRepository`1" "<File>" <|-- FileRepository
@enduml
