@startuml
class FileController {
    + FileController(context:DBContext)
    + <<async>> UploadFile(file:File) : Task<string>
}
ControllerBase <|-- FileController
FileController --> "FileRepository" FileRepository
@enduml
